<a href="https://colab.research.google.com/github/hsmu-jeongeun/deep-learning-practice/blob/main/250402_multi_layer_perceptron.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy 기초 실습

## List to Numpy Array

In [40]:
import numpy as np

In [41]:
test = np.array([[1,2,3], [4,5,6]])
test

array([[1, 2, 3],
       [4, 5, 6]])

### 문제1 : 아래 list 3개를 각각 행으로 갖는 배열을 생성하는 코드를 완성하고 배열의 크기를 print 하세요

In [42]:
list1 = [1,2,3,4]
list2 = [5,6,7,8]
list3 = [9,10,11,12]

# arr = ?
arr = np.array([list1, list2, list3])

print(arr)
print(arr.shape)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
(3, 4)


## Reshape

In [43]:
arr16 = np.array(list(range(16))).reshape((4,4))
arr16

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

### 문제2 : 0부터 15까지의 숫자를 원소로 갖는 배열을 아래의 형태로 만드는 코드를 작성해보세요

In [44]:
# [[ 0,  1],
# [ 2,  3],
# [ 4,  5],
# [ 6,  7],
# [ 8,  9],
# [10, 11],
# [12, 13],
# [14, 15]]

# arr16_reshaped = ?
arr16_reshaped = arr16.reshape((4, 4))

print(arr16_reshaped)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


## 0 or 1 값 채우기

In [45]:
filled_one = np.ones(16)
filled_one

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [46]:
filled_zero = np.zeros((2,5))
filled_zero

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [47]:
filled_like_arr16 = np.ones_like(arr16)
filled_like_arr16

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

### 문제 3 : 아래 형태를 갖는 배열을 만드는 코드를 작성해보세요
- ones, zeros, reshape 사용
- 성공했으면 concatenate의 axis를 0으로 바꿔보고 어떤 동작을 하는지 적어보세요

In [53]:
# arr_with_one 배열 참고
# [[1., 1.],
# [1., 1.],
# [1., 1.],
# [1., 1.]]

# arr_with_zero 배열 참고
# [[0., 0.],
# [0., 0.],
# [0., 0.],
# [0., 0.]]

# arr_with_one_zero 배열 참고
# [[1., 1., 0., 0.],
# [1., 1., 0., 0.],
# [1., 1., 0., 0.],
# [1., 1., 0., 0.]]

# arr_with_one = ?
# arr_with_zero = ?

arr_with_one = np.ones((4,2))
arr_with_zero = np.zeros((4,2))
arr_with_one_zero = np.concatenate((arr_with_one, arr_with_zero), axis=0) # 수평으로 배열 합치기
arr_with_one_zero

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

## Broadcasting

In [54]:
bc = np.ones(25).reshape((5,5))
bc = bc * 5 - 1
bc

array([[4., 4., 4., 4., 4.],
       [4., 4., 4., 4., 4.],
       [4., 4., 4., 4., 4.],
       [4., 4., 4., 4., 4.],
       [4., 4., 4., 4., 4.]])

In [55]:
bc2 = bc * 0 + 3
bc + bc2

array([[7., 7., 7., 7., 7.],
       [7., 7., 7., 7., 7.],
       [7., 7., 7., 7., 7.],
       [7., 7., 7., 7., 7.],
       [7., 7., 7., 7., 7.]])

In [56]:
one_dim_arr = [5, 5, 5, 5, 5]
new_bc = bc + one_dim_arr
new_bc

array([[9., 9., 9., 9., 9.],
       [9., 9., 9., 9., 9.],
       [9., 9., 9., 9., 9.],
       [9., 9., 9., 9., 9.],
       [9., 9., 9., 9., 9.]])

## Slicing

In [57]:
print(arr16)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [58]:
arr16[2]

array([ 8,  9, 10, 11])

In [59]:
arr16[2,:]

array([ 8,  9, 10, 11])

In [60]:
arr16[:,2]

array([ 2,  6, 10, 14])

In [61]:
print(arr16[0:2])
print(arr16[0,2])

[[0 1 2 3]
 [4 5 6 7]]
2


In [62]:
arr16[1:3]

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [63]:
arr16[arr16[:,0]<5]

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

### 문제 4 : 3번째 열에서(index=2) 10보다 크거나 같은 원소가 있는 행 전체를 담는 배열을 생성해보세요

In [64]:
# 결과
# [ 8,  9, 10, 11],
# [12, 13, 14, 15]]

# test_arr = arr16[?]
test_arr = arr16[arr16[:, 2]>= 10]
print(test_arr)

[[ 8  9 10 11]
 [12 13 14 15]]


## 평균(mean)

In [65]:
target = np.ones((10000,100))
target.shape

(10000, 100)

In [66]:
mean = target.mean(axis=0)
print(mean.shape)
print(mean)

(100,)
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1.]


In [67]:
mean = target.mean(axis=1)
print(mean.shape)
print(mean)

(10000,)
[1. 1. 1. ... 1. 1. 1.]


# 코드를 통해서 XOR 문제 해결하기

In [68]:
# 가중치와 바이어스
w11 = np.array([-2, -2])
w12 = np.array([2, 2])
w2 = np.array([1, 1])

b1 = 3
b2 = -1
b3 = -1

In [69]:
# 퍼셉트론
def MLP(x, w, b):
    y = np.sum(w * x) + b

    if y <= 0:
        return 0
    else:
        return 1

In [70]:
# NAND 게이트
def NAND(x1,x2):
    return MLP(np.array([x1, x2]), w11, b1)

# OR 게이트
def OR(x1,x2):
    return MLP(np.array([x1, x2]), w12, b2)

# AND 게이트
def AND(x1,x2):
    return MLP(np.array([x1, x2]), w2, b3)

# XOR 게이트
def XOR(x1,x2):
    return AND(NAND(x1, x2),OR(x1,x2))

In [71]:
# x1, x2 값을 번갈아 대입해 가며 최종 값 출력
for x in [(0, 0), (1, 0), (0, 1), (1, 1)]:
    y = XOR(x[0], x[1])
    print("입력 값: " + str(x) + " 출력 값: " + str(y))

입력 값: (0, 0) 출력 값: 0
입력 값: (1, 0) 출력 값: 1
입력 값: (0, 1) 출력 값: 1
입력 값: (1, 1) 출력 값: 0


# Multi Perceptron Class 생성을 통해 해결하기

In [72]:
# XOR 문제를 해결하기 위한 다층 퍼셉트론
class SimpleMLP:
    def __init__(self):
        # 수동으로 설정한 가중치와 바이어스
        self.weights_input_hidden = np.array([[-2, 2], [-2, 2]])  # x1, x2 -> n1, n2 계산을 위한 가중치 배열
        self.bias_hidden = np.array([3, -1])  # x1, x2 -> n1, n2

        # 출력층: 1개의 뉴런
        self.weights_hidden_output = np.array([1, 1])  # n1, n2 -> y 가중치
        self.bias_output = -1  # n1, n2 -> y 바이어스

    def forward(self, X):
        # 은닉층 계산
        hidden_input = np.dot(X, self.weights_input_hidden) + self.bias_hidden
        hidden_output = np.where(hidden_input <= 0, 0, 1)
        print(f"hidden_output : {hidden_input}")

        # 출력층 계산
        final_input = np.dot(hidden_output, self.weights_hidden_output) + self.bias_output
        final_output = np.where(final_input <= 0, 0, 1)
        print(f"final_output : {final_input}")

        return final_output

In [73]:
# XOR 데이터셋 정의
XOR_X = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])  # 입력값
XOR_y = np.array([0, 1, 1, 0])  # XOR 출력값

In [74]:
# 모델 초기화
mlp = SimpleMLP()

In [75]:
# 예측
predictions = mlp.forward(XOR_X)
# 결과 출력
print(f"XOR 문제 예측 결과: {predictions}")

hidden_output : [[ 3 -1]
 [ 1  1]
 [ 1  1]
 [-1  3]]
final_output : [0 1 1 0]
XOR 문제 예측 결과: [0 1 1 0]


In [76]:
# x1, x2 값을 번갈아 대입해 가며 최종 값 출력
for x in [(0, 0), (1, 0), (0, 1), (1, 1)]:
    y = NAND(x[0], x[1])
    print("입력 값: " + str(x) + " 출력 값: " + str(y))

입력 값: (0, 0) 출력 값: 1
입력 값: (1, 0) 출력 값: 1
입력 값: (0, 1) 출력 값: 1
입력 값: (1, 1) 출력 값: 0


In [77]:
# NAND...

# function

# b > 0
# w1 + b > 0
# w2 + b > 0
# w1 + w2 + b <= 0

# NAND Gate에 해당하는 가중치
w11 = np.array([-2, -2])
b1 = 3

In [78]:
# OR...

# function

# b <= 0
# w1 + b > 0
# w2 + b > 0
# w1 + w2 + b > 0

# OR Gate에 해당하는 가중치
w12 = np.array([2, 2])
b2 = -1

In [80]:
# 다층 퍼셉트론은 딥러닝의 기초 구조

# 딥러닝에서 가장 중요하게 결정하는 요소
# 활성화 함수

# 딥러닝과 다른 점
# 가중치와 바이어스를 구한 후 활성화 함수를 적용